### ISSUE TITLE
agemat.exe not found

### ISSUE THREAD

**Issue by melissamonk-NOAA** [nwfsc-assess/nwfscAgeingError#14]
When I run my 2019 gopher code and also the simulated exampled, I get the error: Error in RunFn(Data = AgeReads2, SigOpt = SigOpt, KnotAges = KnotAges,  :   executable 'agemat.exe' 
It's not writing the agemat.exe to the subfolders. Am I forgetting something?  It's been a few years...

**Comment by iantaylor-NOAA** [comment]
The location of the executable has moved around over the years and not been well documented.

The best way to get it right now is to go to https://github.com/nwfsc-assess/nwfscAgeingError/actions and click on the most recent GitHub Action for the operating system that you're using. In the case of Windows, that is https://github.com/nwfsc-assess/nwfscAgeingError/actions/runs/790359737. Then look for a download under "Artifacts" at the bottom. For Windows, it's called "agemat_win_exes". Put that executable in the folder where you are running the analysis and hopefully the error will go away.

These executables should really be included under a new release at https://github.com/nwfsc-assess/nwfscAgeingError/releases.

**Comment by melissamonk-NOAA** [comment]
Thank you! That did the trick after I downloaded it and changed SourceFile <- getwd()

**Comment by Nikolai-Klibansky** [comment]
I saw this issue from back in the past from 2021. I'm having this same issue in the distant future, here in 2023. I did manage to find a version of agemat.exe at https://github.com/pfmc-assessments/nwfscAgeingError/tree/main/test, but I'm not sure that's the best version to use. I downloaded it and moved it to "nwfscAgeingError\executables", and then ran the example successfully, so that's good. But I wanted to confirm that this is the right file to grab.

Thanks!! 
Nikolai

**Comment by kellijohnson-NOAA** [comment]
@nikolaifish - are you wanting the ADMB or TMB version?

**Comment by Nikolai-Klibansky** [comment]
Hey Kelli,
I was looking for the ADMB version.

Nikolai

**Comment by kellijohnson-NOAA** [comment]
https://github.com/pfmc-assessments/nwfscAgeingError/releases/tag/v1.3.2

**Comment by Nikolai-Klibansky** [comment]
Kelli,
Thanks for the rapid response!
I hope all is well in Washington.

Nikolai
