### ISSUE TITLE
Create a changelog

### ISSUE THREAD

**Issue by iantaylor-NOAA** [nwfsc-assess/nwfscAgeingError#8]
Recent commit message https://github.com/nwfsc-assess/nwfscAgeingError/commit/db02ad46fa2d085d77f3bce9e5f13e589820a8e8 includes these notes in the commit message:
* AEP [Andre Punt] is working with CSIRO to update ageing error capabilities
* Increased speed based on accounting for a change in how data
are entered in the version that Thorson modified years ago
(that we have been using),
* Improvements to the calculation of the best estimated age,
* Improvements to how effective Ns are calculated,
* Improvements and corrections in the plotting of outputs.

These changes could be described in more detail in the README file. The [example script](https://github.com/nwfsc-assess/nwfscAgeingError/blob/master/examples/Example_with_simulated_data.R) could also be updated if necessary. When asked by email about who would be best to documenting these changes, Andre said "Thorson made the changes I believe". @James-Thorson-NOAA, if this is correct, could you provide any more information? @mhaltuch and @kellijohnson-NOAA feel free to add stuff or suggest changes to this issue as you see fit.

**Comment by James-Thorson-NOAA** [comment]
Sorry, I cannot really maintain this at all in the new position, and also forget who agreed to take it over.  I also don't really remember any details at this point.  I was investigating hump-shaped error rates for Ian Stewart at some point, for sablefish, but I don't think that affects what's up there.

**Comment by iantaylor-NOAA** [comment]
Thanks for the quick response @James-Thorson-NOAA. I think there was confusion in the email thread with Andre about what changes we're talking about, those that took place years ago when you were involved, or those that took place last month (which it seems you had no involvement with).

**Comment by kellijohnson-NOAA** [comment]
@mhaltuch noted that some things in 2014 were added
 - tpl  changes 2 options for bias estimation (she read the code to figure out what is going on)
   - (5) Splines ... needs new parameter lines that are not used unless this option is turned on
   - (6) Linear interpolation between knots ... needs new parameter lines that are not used unless this option is turned on
   - change to the calculation of the best true age ... previous way led to strange output plotting
   - improvement to effective N calculation
 - dat file
   - read in one data set in 2014 with missing entries where there are no double reads instead of reading in multiple data sets as in the 2011
   - allowed the estimation speed to increase in 2014 because of how missing values are treated.
 - R code that functions around the tpl
   - code to simulate data
   - automatically format input data from a csv with readers in columns and double reads in the rows to run in the agemat program creating a dat file
   - plot standardized outputs from the output file (needs help)
   - create a matrix of runs that you want and catalog the output -- `StepwiseFn()`

Some issues still remaining with the code include the following
 - estimated vs true age plot is using the wrong true age, AEP did not recode it 
 - example is out of date; maybe big skate
 - documentation needs to be increased
 - script to create dat file from csv should be turned into a function
