### ISSUE TITLE
Slopes in dat file not produced if ...

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscAgeingError#9]
The two if statements lead to some combinations that don't write anything the dat file.
https://github.com/nwfsc-assess/nwfscAgeingError/blob/1a735ebcbda9b5d7b4d1788629fbf799b342e9d8/R/RunFn.R#L244-L252

For example if MaxAge and PlusAge are equal, which can happen with the simulated data, and MinAge and MinusAge are equal then only the header is written. I am uncertain if a new line needs to be created or if checks should be written that change one of the values or tell users that they must change a value.

**Comment by iantaylor-NOAA** [comment]
These lines in the TPL file suggest to me that executable expects those additional slope parameter lines only when the conditions are met as currently defined:
https://github.com/nwfsc-assess/nwfscAgeingError/blob/master/inst/executables/AGEMAT.TPL#L161-L179
ADMB should ignore the header and having it in place might be useful as a placeholder to help users know that this section is blank.

In short, I think no change is necessary unless you see the model crashing due to bad values in this section.
